[package]
name = "valence_schem"
description = "A library for the Sponge Schematic Format."
documentation.workspace = true
repository = "https://github.com/valence-rs/valence/tree/main/crates/valence_schem"
readme = "README.md"
license.workspace = true
keywords = ["schematics", "minecraft", "deserialization"]
version.workspace = true
edition.workspace = true

[dependencies]
flate2.workspace = true
glam.workspace = true
thiserror.workspace = true
valence_server.workspace = true
valence_nbt = {workspace = true, features = ["valence_ident"]}

[dev-dependencies]
valence.workspace = true
