[package]
name = "dump_schedule"
version.workspace = true
edition.workspace = true
repository.workspace = true
documentation.workspace = true
license.workspace = true
publish = false

[dependencies]
bevy_mod_debugdump.workspace = true
clap.workspace = true
valence.workspace = true
