pub const VELOCITY_PLAYER_INFO_CHANNEL: &str = "velocity:player_info";
pub const VELOCITY_SUPPORTED_VERSION: i32 = 1;
pub const VELOCITY_MODERN_FORWARDING_WITH_KEY: i32 = 2;
pub const VELOCITY_MODERN_FORWARDING_WITH_KEY_V2: i32 = 3;
pub const VELOCITY_MAX_SUPPORTED_VERSION: i32 = 3;
