[package]
name = "valence_network"
version.workspace = true
edition.workspace = true

[features]
default = ["encryption", "compression"] # TODO: remove this.
encryption = ["valence_packet/encryption"]
compression = ["valence_packet/compression"]

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
base64.workspace = true
bevy_app.workspace = true
bevy_ecs.workspace = true
bytes.workspace = true
flume.workspace = true
hmac.workspace = true
num-bigint.workspace = true
rand.workspace = true
rsa-der.workspace = true
rsa.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
sha1.workspace = true
sha2.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true
valence_client.workspace = true
valence_core.workspace = true
valence_entity.workspace = true
valence_packet.workspace = true

[dependencies.reqwest]
workspace = true
default-features = false
# Avoid OpenSSL dependency on Linux.
features = ["rustls-tls", "json"]
