[package]
name = "valence_packet"
version.workspace = true
edition.workspace = true

[features]
encryption = ["dep:aes", "dep:cfb8"]
compression =  ["dep:flate2"]

[dependencies]
valence_core.workspace = true
valence_nbt.workspace = true
valence_build_utils.workspace = true
valence_packet_macros.workspace = true
anyhow.workspace = true
bitfield-struct.workspace = true
byteorder.workspace = true
valence_math.workspace = true
uuid = { workspace = true, features = ["serde"] }
bytes.workspace = true
tracing.workspace = true
bevy_ecs.workspace = true
serde = { workspace = true, features = ["derive"] }
cfb8 = { workspace = true, optional = true }
flate2 = { workspace = true, optional = true }
aes = { workspace = true, optional = true }

[dev-dependencies]
rand.workspace = true

[build-dependencies]
anyhow.workspace = true
heck.workspace = true
proc-macro2.workspace = true
quote.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
valence_build_utils.workspace = true
