name: Report a Bug
description: Is there something not working like you expected? Let us know!
labels: [bug, triage]
body:
  - type: input
    attributes:
      label: Valence Version
      description: What version of Valence are you using? If you are targeting a specific commit or branch, put that instead.
      placeholder: version, branch, or commit hash
    validations:
      required: true
  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Minimal Reproducible Example
      description: Do you have a playground to reproduce this bug? Paste it here. It should be a minimal example that exhibits the behavior. If the problem can be reproduced with one of the examples, just indicate which one instead.
      render: Rust
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Create a server using my sample
        2. Do this...
        3. Do that...
        4. See error
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Checklist
      options:
        - label: I have searched the issues of this repo and believe that this is not a duplicate.
          required: true
        - label: This used to work before.
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Version Numbers? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
