name: Report a Bug
description: Is there something not working like you expected? Let us know!
labels: [bug, triage]
body:
  - type: input
    attributes:
      label: Valence Version
      description: What version of Valence are you using? If you are targeting a specific commit or branch, put that instead.
      placeholder: Version, branch, or commit hash.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing. Include any screenshots or additional information here.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen. 
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Create a server using my sample
        2. Do this...
        3. Do that...
        4. See error
    validations:
      required: true
  - type: textarea
    attributes:
      label: Minimal Reproducible Example
      description: A minimal example that exhibits the behavior. If you have a playground, paste it here. If the problem can be reproduced with one of the examples, just indicate which one instead.
      render: Rust
    validations:
      required: false
