name: Feature Request
description: Do you have an idea for a new feature? Let us know!
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: Describe the problem related to your feature request.
      description: A clear description of what the problem is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the solution you would like.
      description: The solution you propose for the problem presented.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
