[package]
name = "valence_ident"
description = "Parse and create Minecraft's resource identifiers"
readme = "README.md"
version.workspace = true
edition.workspace = true
repository.workspace = true
documentation.workspace = true
license.workspace = true

[dependencies]
thiserror.workspace = true
serde.workspace = true
valence_ident_macros.workspace = true
