[package]
name = "valence_server_core"
version.workspace = true
edition.workspace = true

[dependencies]
bevy_ecs.workspace = true
bevy_app.workspace = true
uuid.workspace = true
rand.workspace = true
valence_protocol.workspace = true