[module]
proxy = "direct"
[[module.imports]]
path = "github.com/google/docsy"
[[module.imports]]
path = "github.com/google/docsy/dependencies"

[languages.en]
title = "Docsy"
description = "Docsy er operativsystem for skyen"
languageName ="English"
contentDir = "content/en"
time_format_default = "02.01.2006"
time_format_blog = "02.01.2006"