[package]
name = "valence_instance"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
arrayvec.workspace = true
bevy_app.workspace = true
bevy_ecs.workspace = true
glam.workspace = true
num-integer.workspace = true
parking_lot.workspace = true
rand.workspace = true
rustc-hash.workspace = true
valence_biome.workspace = true
valence_block.workspace = true
valence_core.workspace = true
valence_dimension.workspace = true
valence_entity.workspace = true
valence_nbt.workspace = true
valence_registry.workspace = true
