[package]
name = "valence_inventory"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
bevy_app.workspace = true
bevy_ecs.workspace = true
tracing.workspace = true
valence_client.workspace = true
valence_core.workspace = true
